### ISSUE TITLE
Multiple file support

### ISSUE THREAD

**Issue by Quidam2k** [HenestrosaDev/audiotext#13]
Overview
------------------

Allow more than one file to be selected for transcription. 

Add a checkbox to skip files that already have transcriptions. 

Add the ability to have it monitor a list of folders periodically and transcribe everything in them.

**Comment by HenestrosaDev** [comment]
Thanks for your suggestions. I'll have to think about them, because I don't see how they can be implemented in Audiotext, since they go against the premise of generating the transcription of an audio, displaying it in the text box for editing it (if necessary), and then letting the users save it whenever they want. I think it would be more appropriate to write a command line program for this using WhisperX, which is something that I would be willing to do.

However, as I said, I'll try to find a way to implement it in Audiotext, although it's unlikely.

**Comment by Quidam2k** [comment]
Ah, sorry, hadn't realized the premise what that specific. I'll look for another repo or, as you said, just put together a command line script. Thanks for the response!

**Comment by HenestrosaDev** [comment]
I've just released a new version that supports transcriptions of entire directories. Check it out to see if it does what you are looking for. I need to add the "checkbox to skip files that already have transcriptions", although I don't plan to include "the ability to have it monitor a list of folders periodically and transcribe everything in them".

**Comment by HenestrosaDev** [comment]
Feature added in #27. I ended up not adding an option, but handling the logic internally. See the [Transcribe From](https://github.com/HenestrosaDev/audiotext?tab=readme-ov-file#transcribe-from) section of the README for more information.
