### ISSUE TITLE
Bundle the app

### ISSUE THREAD

**Issue by olawalejuwonm** [HenestrosaDev/audiotext#65]
How do i bundle the app locally using pyinstaller? and Is there like a build.json file that can be used with py to exe https://pypi.org/project/auto-py-to-exe/?

**Comment by HenestrosaDev** [comment]
Open the command line and do the following:

1. Install the `pyinstaller` package by running `pip install pyinstaller`.
2. Go to the root of the project folder (e.g., `cd path/to/audiotext`).
3. Run `pyinstaller audiotext.spec`.

**NOTE**: Use the `audiotext.spec` file from the `dev` branch, as I have made some adjustments to make it work on macOS that I haven't yet merged into the `main` branch.

---

`auto-py-to-exe` is a GUI wrapper for `pyinstaller`. In fact, the following is taken from the [`auto-py-to-exe` repository](https://github.com/brentvollebregt/auto-py-to-exe):

>A .py to .exe converter using a simple graphical interface and [PyInstaller](https://pyinstaller.readthedocs.io/en/stable/index.html) in Python.

I haven't used it, but I'm not aware of the `build.json` file you mention. Regardless, I don't plan to support `auto-py-to-exe`, since `pyinstaller` already serves the purpose of generating the executable of the program.
