### ISSUE TITLE
Building the app with the whisper model

### ISSUE THREAD

**Issue by olawalejuwonm** [HenestrosaDev/audiotext#66]
Open the command line and do the following:

1. Install the `pyinstaller` package by running `pip install pyinstaller`.
2. Go to the root of the project folder (e.g., `cd path/to/audiotext`).
3. Run `pyinstaller audiotext.spec`.

**NOTE**: Use the `audiotext.spec` file from the `dev` branch, as I have made some adjustments to make it work on macOS that I haven't yet merged into the `main` branch.

---

`auto-py-to-exe` is a GUI wrapper for `pyinstaller`. In fact, the following is taken from the [`auto-py-to-exe` repository](https://github.com/brentvollebregt/auto-py-to-exe):

>A .py to .exe converter using a simple graphical interface and [PyInstaller](https://pyinstaller.readthedocs.io/en/stable/index.html) in Python.

I haven't used it, but I'm not aware of the `build.json` file you mention. Regardless, I don't plan to support `auto-py-to-exe`, since `pyinstaller` already serves the purpose of generating the executable of the program.

_Originally posted by @HenestrosaDev in https://github.com/HenestrosaDev/audiotext/issues/65#issuecomment-2352359849_

If I have already downloaded the whisperX models will it come with the built app so that there won't be any need for it to download again when it's being used

**Comment by HenestrosaDev** [comment]
>If I have already downloaded the whisperX models will it come with the built app so that there won't be any need for it to download again when it's being used

No, because the WhisperX models are downloaded from HuggingFace. They are stored in the following path if you are on Windows: `C:\Users\<user>\.cache\huggingface\hub`. However, if you generate the executable with PyInstaller and run it on a machine where you have already downloaded the model(s), you won't need to download it again, because WhisperX will check the aforementioned path to determine if the model you selected is already there.

**Comment by olawalejuwonm** [comment]
That's not the case.

It always re download and I do not know why

**Comment by HenestrosaDev** [comment]
What's your operating system?

**Comment by olawalejuwonm** [comment]
Windows

**Comment by HenestrosaDev** [comment]
Can you check the path `C:\Users\<user>\.cache\huggingface\hub` and tell me what's there? Make sure your replace `<user>` with your actual username.

**Comment by HenestrosaDev** [comment]
You can, but I don't understand why you said that the model is always downloaded again, since WhisperX always checks the above path for using the models. Besides, considering the way Audiotext is programmed, there is no way that the model will be downloaded to a different directory, and the fact that you run it from the executable generated by PyInstaller doesn't change this behavior. How do you know that the model(s) gets downloaded again? 

Also, just to be sure, be aware that if you have only downloaded the `large-v2` model and want to use the `small` model for the first time, the latter will be downloaded, regardless of whether you run Audiotext from an executable created by PyInstaller or not.

**Comment by olawalejuwonm** [comment]
Thanks for your explanation.

For MacOS what part is the model downloaded to?

**Comment by HenestrosaDev** [comment]
On macOS, it is `~/. cache/huggingface/hub`
