### ISSUE TITLE
HELP!!!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [HenestrosaDev/audiotext#9]
HELLO MAN...CONGRATULATIONS FOR YOUR AMAZING PROJECT!!!BUT COULD YOU PLEASE TELL ME STEP BY STEP WHAT I HAVE TO DO FOR USE YOUR AMAZING PROJECT?I AM NEW ON THIS AND I DONT KNOW!!!

**Comment by HenestrosaConH** [comment]
Hello.

What OS are you using? If you are on Windows, you just need to download the `.exe` from [the latest release](https://github.com/HenestrosaConH/audiotext/releases/tag/v1.2.4) and open it to start using it.

**Comment by KENPOKASMMA1982** [comment]
my friend appear error generating the file transcription

**Comment by HenestrosaConH** [comment]
I cannot help you without more information about the error. Please fill out this form so I can provide further assistance:

Steps to reproduce
------------------

1. (How do you make the issue happen? Does it happen every time you try it?)
2. (Make sure to go into as much detail as needed to reproduce the issue.)
3. (If there are any files, like any `strings.xml`, don't forget to include them.)

Expected behaviour
------------------

(What did you expect to happen?)

Actual behaviour
----------------

(What happened instead? How is it different from what you expected?)

```
(If the library threw an exception, paste the full stack trace here)
```

System information
------------------

(Delete all statements that don't apply.)

- **System**: (For example, "Ubuntu 20.04 LTS x64", "Windows 11 x64", or "macOS Monterey")
- **System language**: (Please, indicate the region as well)
- **Audiotext version**: 


Code To Duplicate
------------------

Delete this section if you didn't modify the code.

A **short** program that isolates and demonstrates the problem (Do not paste your massive program, but instead 10-20 lines that clearly show the problem).

This pre-formatted code block is all set for you to paste in your bit of code:

```python
# Paste your code here
```

Screenshot, Sketch, or Drawing
---------------------

Optional. Feel free to provide an image if you think it adds more useful information to the issue.

You can use [this tool](https://www.cockos.com/licecap/) to record GIFs on macOS and Windows, and [this tool](https://github.com/colinkeenan/silentcast) or [this tool](https://github.com/GNOME/byzanz) on Linux.

**Comment by HenestrosaDev** [comment]
Closed due to stale status. If you want to provide more information about the problem you encountered, please open a new issue.
